version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/paper-management
      - JWT_SECRET=THIS_IS_A_SECRET_KEY_FOR_DOCKER
      - PORT=5000
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
